version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - monitor-net
    volumes:
      - mongo-data:/data/db

  users:
    container_name: users
    image: ghcr.io/arquisoft/yovi_es4d-users:latest
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/usersdb
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - monitor-net

  webapp:
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es4d-webapp:latest
    environment:
      - VITE_API_URL=http://gateway:8000
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es4d-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  game:
    container_name: game
    image: ghcr.io/arquisoft/yovi_es4d-game:latest
    ports:
      - "8003:8003"
    networks:
      - monitor-net

  gateway:
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_es4d-gateway:latest
    ports:
      - "8000:8000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo-data:
