version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - monitor-net
    volumes:
      - mongo-data:/data/db

  users:
    container_name: users
    image: ghcr.io/arquisoft/yovi_es4d-users:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "${USERS_PORT}:3000"
    depends_on:
      - mongodb
    networks:
      - monitor-net

  webapp:
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es4d-webapp:latest
    environment:
      - VITE_API_URL=http://gateway:8000   # <- cambio aquÃ­
    ports:
      - "${WEBAPP_PORT}:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gateway:
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_es4d-gateway:latest
    ports:
      - "${GATEWAY_PORT}:8000"
    networks:
      - monitor-net

  game:
    container_name: game
    image: ghcr.io/arquisoft/yovi_es4d-game:latest
    ports:
      - "${GAME_PORT}:8003"
    networks:
      - monitor-net

  gamey:
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es4d-gamey:latest
    ports:
      - "${GAMEY_PORT}:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo-data: